using Microsoft.SharePoint.Client;
using Microsoft.SharePoint.Client.Publishing;
using SPMeta2.Containers.Assertion;
using SPMeta2.CSOM.Extensions;
using SPMeta2.CSOM.ModelHosts;
using SPMeta2.CSOM.Standard.ModelHandlers;
using SPMeta2.Definitions;
using SPMeta2.Regression.CSOM.Standard.Extensions;
using SPMeta2.Standard.Definitions;
using SPMeta2.Utils;

namespace SPMeta2.Regression.CSOM.Standard.Validation
{
    public class DesignPackageDefinitionValidator : DesignPackageModelHandler
    {
        #region methods

        public override void DeployModel(object modelHost, DefinitionBase model)
        {
            var siteModelHost = modelHost.WithAssertAndCast<SiteModelHost>("modelHost", value => value.RequireNotNull());
            var definition = model.WithAssertAndCast<DesignPackageDefinition>("model", value => value.RequireNotNull());

            var spObject = this.FindExistingSolutionById(siteModelHost, definition.SolutionId);
            var context = spObject.Context;

            var site = siteModelHost.HostSite;
            var rootWeb = site.RootWeb;

            var fileItem = spObject.ListItemAllFields;

            context.Load(fileItem);
            context.Load(rootWeb, w => w.AllProperties);

            context.ExecuteQueryWithTrace();

            var assert = ServiceFactory.AssertService.NewAssert(definition, fileItem);

            assert
                .ShouldNotBeNull(fileItem)

                //.ShouldBeEqual(d => d, o => o.GetSolutionActivationStatus())
                .ShouldBeEqual(d => d.SolutionId, o => o.GetSolutionId())

                .SkipProperty(d => d.Content, "Content is fine.")
                .SkipProperty(d => d.FileName, "Randomly generated by CSOM activation.");

            if (definition.Apply)
            {
                assert.ShouldBeEqual((p, s, d) =>
                {
                    // once applied, design package sets AppliedDesignGuid property in the root web
                    // checking is all good
                    var installedPackageId = ConvertUtils.ToGuid(rootWeb.AllProperties["AppliedDesignGuid"]);

                    var srcProp = s.GetExpressionValue(m => m.Apply);
                    var isValid = spObject != null
                                  && installedPackageId == definition.SolutionId;

                    return new PropertyValidationResult
                    {
                        Tag = p.Tag,
                        Src = srcProp,
                        Dst = null,
                        IsValid = isValid
                    };
                });
            }
            else
            {
                assert.SkipProperty(m => m.Apply, "Apply is false");
            }

            if (definition.Install)
            {
                assert.ShouldBeEqual((p, s, d) =>
                {
                    var srcProp = s.GetExpressionValue(m => m.Install);
                    var isValid = spObject != null;

                    return new PropertyValidationResult
                    {
                        Tag = p.Tag,
                        Src = srcProp,
                        Dst = null,
                        IsValid = isValid
                    };
                });
            }
            else
            {
                assert.SkipProperty(d => d.Install, "Install is false");
            }

            assert.SkipProperty(m => m.MajorVersion, string.Empty);
            assert.SkipProperty(m => m.MinorVersion, string.Empty);
        }

        #endregion
    }
}
