using System;
using SPMeta2.Definitions;
using SPMeta2.Enumerations;
using SPMeta2.Syntax.Default;

// <auto-generated>
//     This code was generated by SPMeta2 T4 file.
//
//     Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
// </auto-generated>

namespace SPMeta2.T4.Model
{
    public static class T4SPContentType
    {
        #region properties

		public static ContentTypeDefinition T4Item = new ContentTypeDefinition
		{
			Id = new Guid("{53636C11-760D-41DB-8712-3150EA6A7D60}"),
			Name = "T4 Item",
			Description = "T4 generated item content type.",
			Group = "SPMeta2 T4 Content Types",
			ParentContentTypeId = BuiltInContentTypeId.Item
		};


		public static ContentTypeDefinition T4Document = new ContentTypeDefinition
		{
			Id = new Guid("{F7789024-DAE6-46E6-934C-3BA342D2EE58}"),
			Name = "T4 Document",
			Description = "T4 document content type.",
			Group = "SPMeta2 T4 Content Types",
			ParentContentTypeId = BuiltInContentTypeId.Document
		};


		public static ContentTypeDefinition T4ItemChild = new ContentTypeDefinition
		{
			Id = new Guid("{580A131E-D4E1-45C6-8376-E9B372FD77FC}"),
			Name = "T4 Item Child",
			Description = String.Empty,
			Group = "SPMeta2 T4 Content Types",
			ParentContentTypeId = T4Item.GetContentTypeId()
		};


		public static ContentTypeDefinition T4DocumentChild = new ContentTypeDefinition
		{
			Id = new Guid("{72A842E5-1D94-4137-84FC-539294D4DFB2}"),
			Name = "T4 Document Child",
			Description = String.Empty,
			Group = "SPMeta2 T4 Content Types",
			ParentContentTypeId = T4Document.GetContentTypeId()
		};


		public static ContentTypeDefinition T4ItemDoubleChild = new ContentTypeDefinition
		{
			Id = new Guid("{A8B0CD04-AA08-4DDD-8BEC-9D258B633B7C}"),
			Name = "T4 Item Double Child",
			Description = String.Empty,
			Group = "SPMeta2 T4 Content Types",
			ParentContentTypeId = T4ItemChild.GetContentTypeId()
		};


		public static ContentTypeDefinition T4DocumentDoubleChild = new ContentTypeDefinition
		{
			Id = new Guid("{EE68513D-34C8-4F6A-B0B6-B7CA9161CC30}"),
			Name = "T4 Document Double Child",
			Description = String.Empty,
			Group = "SPMeta2 T4 Content Types",
			ParentContentTypeId = T4DocumentChild.GetContentTypeId()
		};

        #endregion
    }
}