using System;
using SPMeta2.Definitions;
using SPMeta2.Enumerations;
using SPMeta2.Syntax.Default;

// <auto-generated>
//     This code was generated by SPMeta2 T4 file.
//
//     Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
// </auto-generated>

namespace SPMeta2.T4.Model
{
    public static class T4SPField
    {
        #region properties

		public static FieldDefinition T4Text = new FieldDefinition
		{
			Id = new Guid("{867667A2-3AA8-4B7C-89C3-8FDFCE8C473B}"),
			Title = "T4 Text",
			InternalName = "spmeta2_t4_T4Text",
			Description = "T4 text column.",
			Group = "SPMeta2 T4 Fields",
			FieldType = BuiltInFieldTypes.Text
		};


		public static FieldDefinition T4Note = new FieldDefinition
		{
			Id = new Guid("{849EF7CA-E203-465A-8532-E79439994FA5}"),
			Title = "T4 Note",
			InternalName = "spmeta2_t4_T4Note",
			Description = "T4 note column.",
			Group = "SPMeta2 T4 Fields",
			FieldType = BuiltInFieldTypes.Note
		};


		public static FieldDefinition T4User = new FieldDefinition
		{
			Id = new Guid("{9ECEA903-8BFE-4FF8-9C96-6EE9A0341FD4}"),
			Title = "T4 User",
			InternalName = "spmeta2_t4_T4User",
			Description = String.Empty,
			Group = "SPMeta2 T4 Fields",
			FieldType = BuiltInFieldTypes.User
		};


		public static FieldDefinition T4Number = new FieldDefinition
		{
			Id = new Guid("{0156DFE6-139B-4CDF-BB8D-35B86EFDC142}"),
			Title = "T4 Number",
			InternalName = "spmeta2_t4_T4Number",
			Description = String.Empty,
			Group = "SPMeta2 T4 Fields",
			FieldType = BuiltInFieldTypes.Number
		};

        #endregion
    }
}