using System;
using SPMeta2.Definitions;
using SPMeta2.Enumerations;

// <auto-generated>
//     This code was generated by SPMeta2 T4 file.
//
//     Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
// </auto-generated>

namespace SPMeta2.T4.Model
{
    public static class T4SPList
    {
        #region properties

		public static ListDefinition T4DocumentLibrary = new ListDefinition
		{
			Title = "T4 Document Library",
			Description = String.Empty,
			Url = "T4DocumentLibrary",
			TemplateType = BuiltInListTemplateTypeId.DocumentLibrary,
			TemplateName = String.Empty,
			ContentTypesEnabled = false
		};


		public static ListDefinition T4List = new ListDefinition
		{
			Title = "T4 List",
			Description = String.Empty,
			Url = "T4List",
			TemplateType = BuiltInListTemplateTypeId.GenericList,
			TemplateName = String.Empty,
			ContentTypesEnabled = true
		};


		public static ListDefinition T4Links = new ListDefinition
		{
			Title = "T4 Links",
			Description = String.Empty,
			Url = "T4Links",
			TemplateType = BuiltInListTemplateTypeId.Links,
			TemplateName = String.Empty,
			ContentTypesEnabled = true
		};


		public static ListDefinition T4Tasks = new ListDefinition
		{
			Title = "T4 Tasks",
			Description = String.Empty,
			Url = "T4Tasks",
			TemplateType = BuiltInListTemplateTypeId.Tasks,
			TemplateName = String.Empty,
			ContentTypesEnabled = true
		};


		public static ListDefinition T4Contacts = new ListDefinition
		{
			Title = "T4 Contacts",
			Description = String.Empty,
			Url = "T4Contacts",
			TemplateType = BuiltInListTemplateTypeId.Contacts,
			TemplateName = String.Empty,
			ContentTypesEnabled = true
		};


		public static ListDefinition T4Announcements = new ListDefinition
		{
			Title = "T4 Announcements",
			Description = String.Empty,
			Url = "T4Announcements",
			TemplateType = BuiltInListTemplateTypeId.Announcements,
			TemplateName = String.Empty,
			ContentTypesEnabled = true
		};

        #endregion
    }
}