using System;
using SPMeta2.Definitions;
using SPMeta2.Enumerations;

// <auto-generated>
//     This code was generated by SPMeta2 T4 file.
//
//     Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
// </auto-generated>

namespace SPMeta2.T4.Model
{
    public static class T4SPListView
    {
        #region properties

		public static ListViewDefinition LastDocuments = new ListViewDefinition
		{
			Title = "Last Documents",
			RowLimit = 30,
			IsDefault = true,
			Query = "",
		};


		public static ListViewDefinition LastEditiedDocuments = new ListViewDefinition
		{
			Title = "Last Editied Documents",
			RowLimit = 10,
			IsDefault = true,
			Query = "",
		};


        #endregion
    }
}