using System;
using SPMeta2.Definitions;
using SPMeta2.Enumerations;

// <auto-generated>
//     This code was generated by SPMeta2 T4 file.
//
//     Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
// </auto-generated>

namespace SPMeta2.T4.Model
{
    public static class T4SPSecurityRole
    {
        #region properties

		public static SecurityRoleDefinition InternalContractors = new SecurityRoleDefinition
		{
			Name = "Internal Contractors",
			Description = "Security role for internal contractors.",
		};


		public static SecurityRoleDefinition ExternalContractors = new SecurityRoleDefinition
		{
			Name = "External Contractors",
			Description = "",
		};


		public static SecurityRoleDefinition FirstYearStudents = new SecurityRoleDefinition
		{
			Name = "First Year Students",
			Description = "",
		};


		public static SecurityRoleDefinition SecondYearStudents = new SecurityRoleDefinition
		{
			Name = "Second Year Students",
			Description = "",
		};

        #endregion
    }
}