using System;
using SPMeta2.Definitions;
using SPMeta2.Enumerations;

// <auto-generated>
//     This code was generated by SPMeta2 T4 file.
//
//     Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
// </auto-generated>

namespace SPMeta2.T4.Model
{
    public static class T4SPWebpartPage
    {
        #region properties

		public static WebPartPageDefinition MainPage = new WebPartPageDefinition
		{
			Title = "Main Page",
			FileName = "MainPage.aspx",
			NeedOverride = true,
			PageLayoutTemplate = 1,
			CustomPageLayout = "",
		};


		public static WebPartPageDefinition HR = new WebPartPageDefinition
		{
			Title = "HR",
			FileName = "HR.aspx",
			NeedOverride = true,
			PageLayoutTemplate = 2,
			CustomPageLayout = "",
		};


		public static WebPartPageDefinition Support = new WebPartPageDefinition
		{
			Title = "Support",
			FileName = "Support.aspx",
			NeedOverride = true,
			PageLayoutTemplate = 1,
			CustomPageLayout = "",
		};


		public static WebPartPageDefinition CustomLangingPage = new WebPartPageDefinition
		{
			Title = "Custom Langing Page",
			FileName = "CustomLangingPage.aspx",
			NeedOverride = true,
			CustomPageLayout = "test!",
		};

        #endregion
    }
}