using System;
using SPMeta2.Definitions;
using SPMeta2.Enumerations;

// <auto-generated>
//     This code was generated by SPMeta2 T4 file.
//
//     Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
// </auto-generated>

namespace SPMeta2.T4.Model
{
    public static class T4SPWebpart
    {
        #region properties

		public static WebPartDefinition Tiles = new WebPartDefinition
		{
			Title = "Tiles",
			Id = "hpTiles",
			ZoneId = "Header",
			ZoneIndex = 10,
			WebpartFileName = "",
			WebpartType = "",
			WebpartXmlTemplate = "<webParts>  <webPart xmlns=\"http://schemas.microsoft.com/WebPart/v3\">    <metaData>      <type name=\"Microsoft.SharePoint.WebPartPages.GettingStartedWebPart, Microsoft.SharePoint, Version=15.0.0.0, Culture=neutral, PublicKeyToken=71e9bce111e9429c\" />      <importErrorMessage>Cannot import this Web Part.</importErrorMessage>    </metaData>    <data>      <properties>        <property name=\"AllowZoneChange\" type=\"bool\">True</property>        <property name=\"HelpUrl\" type=\"string\" />        <property name=\"Hidden\" type=\"bool\">False</property>        <property name=\"MissingAssembly\" type=\"string\">Cannot import this Web Part.</property>        <property name=\"Description\" type=\"string\" />        <property name=\"BaseViewID\" type=\"string\">2</property>        <property name=\"AllowHide\" type=\"bool\">True</property>        <property name=\"AllowMinimize\" type=\"bool\">True</property>        <property name=\"Title\" type=\"string\">Get started with your site</property>        <property name=\"TitleUrl\" type=\"string\" />        <property name=\"ExportMode\" type=\"exportmode\">All</property>        <property name=\"ChromeType\" type=\"chrometype\">None</property>        <property name=\"AllowConnect\" type=\"bool\">True</property>        <property name=\"Width\" type=\"string\" />        <property name=\"Height\" type=\"string\" />        <property name=\"CatalogIconImageUrl\" type=\"string\" />        <property name=\"HelpMode\" type=\"helpmode\">Modeless</property>        <property name=\"AllowEdit\" type=\"bool\">True</property>        <property name=\"TitleIconImageUrl\" type=\"string\" />        <property name=\"Direction\" type=\"direction\">NotSet</property>        <property name=\"AllowClose\" type=\"bool\">True</property>        <property name=\"ChromeState\" type=\"chromestate\">Normal</property>      </properties>    </data>  </webPart></webParts>",
		};


		public static WebPartDefinition Newsfeed = new WebPartDefinition
		{
			Title = "Newsfeed",
			Id = "hpNewsfeed",
			ZoneId = "Header",
			ZoneIndex = 20,
			WebpartFileName = "",
			WebpartType = "",
			WebpartXmlTemplate = "<?xml version=\"1.0\" encoding=\"utf-8\"?><WebPart xmlns:xsd=\"http://www.w3.org/2001/XMLSchema\" xmlns:xsi=\"http://www.w3.org/2001/XMLSchema-instance\" xmlns=\"http://schemas.microsoft.com/WebPart/v2\">  <Title>Site Feed</Title>  <FrameType>None</FrameType>  <Description>Site Feed contains microblogging conversations on a group site.</Description>  <IsIncluded>true</IsIncluded>  <ZoneID>wpz</ZoneID>  <PartOrder>1</PartOrder>  <FrameState>Normal</FrameState>  <Height />  <Width />  <AllowRemove>true</AllowRemove>  <AllowZoneChange>true</AllowZoneChange>  <AllowMinimize>true</AllowMinimize>  <AllowConnect>true</AllowConnect>  <AllowEdit>true</AllowEdit>  <AllowHide>true</AllowHide>  <IsVisible>true</IsVisible>  <DetailLink />  <HelpLink />  <HelpMode>Modeless</HelpMode>  <Dir>Default</Dir>  <PartImageSmall />  <MissingAssembly>Cannot import this Web Part.</MissingAssembly>  <PartImageLarge />  <IsIncludedFilter />  <Assembly>Microsoft.SharePoint.Portal, Version=15.0.0.0, Culture=neutral, PublicKeyToken=71e9bce111e9429c</Assembly>  <TypeName>Microsoft.SharePoint.Portal.WebControls.SiteFeedWebPart</TypeName></WebPart>",
		};


        #endregion
    }
}