using System;
using SPMeta2.Definitions;
using SPMeta2.Enumerations;

// <auto-generated>
//     This code was generated by SPMeta2 T4 file.
//
//     Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
// </auto-generated>

namespace SPMeta2.T4.Model
{
    public static class T4SPWeb
    {
        #region properties

		public static WebDefinition Projects = new WebDefinition
		{
			Title = "Projects",
			Description = "Projects repository.",
			WebTemplate = "STS#0",
			Url = "Projects",
		};


		public static WebDefinition Teams = new WebDefinition
		{
			Title = "Teams",
			Description = "Teams site.",
			WebTemplate = "STS#0",
			Url = "Teams",
		};


		public static WebDefinition Marketing = new WebDefinition
		{
			Title = "Marketing",
			Description = String.Empty,
			WebTemplate = "STS#0",
			Url = "Marketing",
		};


		public static WebDefinition HR = new WebDefinition
		{
			Title = "HR",
			Description = String.Empty,
			WebTemplate = "STS#0",
			Url = "HR",
		};


		public static WebDefinition IT = new WebDefinition
		{
			Title = "IT",
			Description = String.Empty,
			WebTemplate = "STS#0",
			Url = "IT",
		};


		public static WebDefinition Accounting = new WebDefinition
		{
			Title = "Accounting",
			Description = String.Empty,
			WebTemplate = "STS#0",
			Url = "Accounting",
		};


        #endregion
    }
}