using System;
using SPMeta2.Definitions;
using SPMeta2.Enumerations;

// <auto-generated>
//     This code was generated by SPMeta2 T4 file.
//
//     Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
// </auto-generated>

namespace SPMeta2.T4.Model
{
    public static class T4SPWikiPage
    {
        #region properties

		public static WikiPageDefinition MainWikiPage = new WikiPageDefinition
		{
			Title = "Main Wiki Page",
			FileName = "MainWikiPage.aspx",
			NeedOverride = true,
		};


		public static WikiPageDefinition HRWiki = new WikiPageDefinition
		{
			Title = "HR Wiki",
			FileName = "HRWiki.aspx",
			NeedOverride = true,
		};


		public static WikiPageDefinition SupportWikiPage = new WikiPageDefinition
		{
			Title = "Support Wiki Page",
			FileName = "SupportWikiPage.aspx",
			NeedOverride = true,
		};


		public static WikiPageDefinition CustomLangingWikiPage = new WikiPageDefinition
		{
			Title = "Custom Langing Wiki Page",
			FileName = "CustomLangingWikiPage.aspx",
			NeedOverride = true,
		};

        #endregion
    }
}