//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34014
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SPMeta2.Containers {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class DefaultMasterPagePreviewTemplates {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal DefaultMasterPagePreviewTemplates() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SPMeta2.Containers.DefaultMasterPagePreviewTemplates", typeof(DefaultMasterPagePreviewTemplates).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Palette001.spcolor
        ///[SECTION]
        ///SharePointPersonality.spfont
        ///[SECTION]
        ///[ID] .dgp-pageHyperLinkVisited
        ///{
        ///    color: [T_THEME_COLOR_HYPERLINKFOLLOWED] !important;
        ///}
        ///[ID] #dgp-pageContainer
        ///{
        ///    background-color: [T_THEME_COLOR_PAGEBACKGROUND];
        ///    color: [T_THEME_COLOR_BODYTEXT];
        ///    width: 100%;
        ///    height:100%;     
        ///    background-image: url(&apos;[T_IMAGE]&apos;);       
        ///    background-size: cover;
        ///    font-family: [T_BODY_FONT];   
        ///}
        ///[ID] .dgp-pageContent
        ///{
        ///    width: 100%;
        ///    height:100%;
        ///     [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Oslo {
            get {
                return ResourceManager.GetString("Oslo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Palette001.spcolor
        ///[SECTION]
        ///SharePointPersonality.spfont
        ///[SECTION]
        ///[ID] .dgp-pageHyperLinkVisited
        ///{
        ///    color: [T_THEME_COLOR_HYPERLINKFOLLOWED] !important;
        ///}
        ///[ID] #dgp-pageContainer
        ///{
        ///    width: 100%;
        ///    height:100%;
        ///    position: relative;
        ///    color: [T_THEME_COLOR_BODYTEXT]; 
        ///    background-color: [T_THEME_COLOR_PAGEBACKGROUND];
        ///    font-size: 1.0em;
        ///    font-family: [T_BODY_FONT];
        ///}
        ///[ID] .dgp-pageContent
        ///{
        ///    width: 100%;
        ///    height:100%;
        ///    position: relative;
        ///    z-index: 10 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Seattle {
            get {
                return ResourceManager.GetString("Seattle", resourceCulture);
            }
        }
    }
}
