//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18408
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SPMeta2.Containers {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class DefaultMasterPageTemplates {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal DefaultMasterPageTemplates() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SPMeta2.Containers.DefaultMasterPageTemplates", typeof(DefaultMasterPageTemplates).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;%@ Master Language=&quot;C#&quot; %&gt;
        ///&lt;%@ Register Tagprefix=&quot;SharePoint&quot; Namespace=&quot;Microsoft.SharePoint.WebControls&quot; Assembly=&quot;Microsoft.SharePoint, Version=15.0.0.0, Culture=neutral, PublicKeyToken=71e9bce111e9429c&quot; %&gt; &lt;%@ Register Tagprefix=&quot;Utilities&quot; Namespace=&quot;Microsoft.SharePoint.Utilities&quot; Assembly=&quot;Microsoft.SharePoint, Version=15.0.0.0, Culture=neutral, PublicKeyToken=71e9bce111e9429c&quot; %&gt; &lt;%@ Import Namespace=&quot;Microsoft.SharePoint&quot; %&gt; &lt;%@ Assembly Name=&quot;Microsoft.Web.CommandUI, Version=15.0.0.0, Culture=n [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Minimal {
            get {
                return ResourceManager.GetString("Minimal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;%@Master language=&quot;C#&quot;%&gt;
        ///&lt;%@ Register Tagprefix=&quot;SharePoint&quot; Namespace=&quot;Microsoft.SharePoint.WebControls&quot; Assembly=&quot;Microsoft.SharePoint, Version=15.0.0.0, Culture=neutral, PublicKeyToken=71e9bce111e9429c&quot; %&gt; &lt;%@ Register Tagprefix=&quot;Utilities&quot; Namespace=&quot;Microsoft.SharePoint.Utilities&quot; Assembly=&quot;Microsoft.SharePoint, Version=15.0.0.0, Culture=neutral, PublicKeyToken=71e9bce111e9429c&quot; %&gt; &lt;%@ Import Namespace=&quot;Microsoft.SharePoint&quot; %&gt; &lt;%@ Assembly Name=&quot;Microsoft.Web.CommandUI, Version=15.0.0.0, Culture=neu [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Oslo {
            get {
                return ResourceManager.GetString("Oslo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;%@Master language=&quot;C#&quot;%&gt;
        ///&lt;%@ Register Tagprefix=&quot;SharePoint&quot; Namespace=&quot;Microsoft.SharePoint.WebControls&quot; Assembly=&quot;Microsoft.SharePoint, Version=15.0.0.0, Culture=neutral, PublicKeyToken=71e9bce111e9429c&quot; %&gt; &lt;%@ Register Tagprefix=&quot;Utilities&quot; Namespace=&quot;Microsoft.SharePoint.Utilities&quot; Assembly=&quot;Microsoft.SharePoint, Version=15.0.0.0, Culture=neutral, PublicKeyToken=71e9bce111e9429c&quot; %&gt; &lt;%@ Import Namespace=&quot;Microsoft.SharePoint&quot; %&gt; &lt;%@ Assembly Name=&quot;Microsoft.Web.CommandUI, Version=15.0.0.0, Culture=neu [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Seattle {
            get {
                return ResourceManager.GetString("Seattle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;form runat=&quot;server&quot; onsubmit=&quot;if (typeof(_spFormOnSubmitWrapper) != &apos;undefined&apos;) {return _spFormOnSubmitWrapper();} else {return true;}&quot;&gt;
        ///  &lt;asp:ScriptManager id=&quot;ScriptManager&quot; runat=&quot;server&quot; EnablePageMethods=&quot;false&quot; EnablePartialRendering=&quot;true&quot; EnableScriptGlobalization=&quot;false&quot; EnableScriptLocalization=&quot;true&quot; /&gt;
        ///	&lt;WebPartPages:SPWebPartManager id=&quot;m&quot; runat=&quot;Server&quot;/&gt;
        ///&lt;SharePoint:SPNoScript runat=&quot;server&quot;/&gt;
        ///&lt;div id=&quot;TurnOnAccessibility&quot; style=&quot;display:none&quot; class=&quot;s4-notdlg noindex&quot;&gt;
        ///	&lt;a id=&quot;linkTu [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string V4 {
            get {
                return ResourceManager.GetString("V4", resourceCulture);
            }
        }
    }
}
