//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SPMeta2.Templates {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class SP2016WebPartPageTemplates {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal SP2016WebPartPageTemplates() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SPMeta2.Templates.SP2016WebPartPageTemplates", typeof(SP2016WebPartPageTemplates).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;%-- _lcid=&quot;1033&quot; _version=&quot;16.0.4266&quot; _dal=&quot;1&quot; --%&gt;
        ///&lt;%-- _LocalBinding --%&gt;
        ///&lt;%@ Page language=&quot;C#&quot; MasterPageFile=&quot;~masterurl/default.master&quot;    Inherits=&quot;Microsoft.SharePoint.WebPartPages.WebPartPage,Microsoft.SharePoint,Version=16.0.0.0,Culture=neutral,PublicKeyToken=71e9bce111e9429c&quot;  %&gt; &lt;%@ Register Tagprefix=&quot;SharePoint&quot; Namespace=&quot;Microsoft.SharePoint.WebControls&quot; Assembly=&quot;Microsoft.SharePoint, Version=16.0.0.0, Culture=neutral, PublicKeyToken=71e9bce111e9429c&quot; %&gt; &lt;%@ Register Tagprefix=&quot;Utilities [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string spstd1 {
            get {
                return ResourceManager.GetString("spstd1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;%-- _lcid=&quot;1033&quot; _version=&quot;16.0.4266&quot; _dal=&quot;1&quot; --%&gt;
        ///&lt;%-- _LocalBinding --%&gt;
        ///&lt;%@ Page language=&quot;C#&quot; MasterPageFile=&quot;~masterurl/default.master&quot;    Inherits=&quot;Microsoft.SharePoint.WebPartPages.WebPartPage,Microsoft.SharePoint,Version=16.0.0.0,Culture=neutral,PublicKeyToken=71e9bce111e9429c&quot;  %&gt; &lt;%@ Register Tagprefix=&quot;SharePoint&quot; Namespace=&quot;Microsoft.SharePoint.WebControls&quot; Assembly=&quot;Microsoft.SharePoint, Version=16.0.0.0, Culture=neutral, PublicKeyToken=71e9bce111e9429c&quot; %&gt; &lt;%@ Register Tagprefix=&quot;Utilities [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string spstd2 {
            get {
                return ResourceManager.GetString("spstd2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;%-- _lcid=&quot;1033&quot; _version=&quot;16.0.4266&quot; _dal=&quot;1&quot; --%&gt;
        ///&lt;%-- _LocalBinding --%&gt;
        ///&lt;%@ Page language=&quot;C#&quot; MasterPageFile=&quot;~masterurl/default.master&quot;    Inherits=&quot;Microsoft.SharePoint.WebPartPages.WebPartPage,Microsoft.SharePoint,Version=16.0.0.0,Culture=neutral,PublicKeyToken=71e9bce111e9429c&quot;  %&gt; &lt;%@ Register Tagprefix=&quot;SharePoint&quot; Namespace=&quot;Microsoft.SharePoint.WebControls&quot; Assembly=&quot;Microsoft.SharePoint, Version=16.0.0.0, Culture=neutral, PublicKeyToken=71e9bce111e9429c&quot; %&gt; &lt;%@ Register Tagprefix=&quot;Utilities [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string spstd3 {
            get {
                return ResourceManager.GetString("spstd3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;%-- _lcid=&quot;1033&quot; _version=&quot;16.0.4266&quot; _dal=&quot;1&quot; --%&gt;
        ///&lt;%-- _LocalBinding --%&gt;
        ///&lt;%@ Page language=&quot;C#&quot; MasterPageFile=&quot;~masterurl/default.master&quot;    Inherits=&quot;Microsoft.SharePoint.WebPartPages.WebPartPage,Microsoft.SharePoint,Version=16.0.0.0,Culture=neutral,PublicKeyToken=71e9bce111e9429c&quot;  %&gt; &lt;%@ Register Tagprefix=&quot;SharePoint&quot; Namespace=&quot;Microsoft.SharePoint.WebControls&quot; Assembly=&quot;Microsoft.SharePoint, Version=16.0.0.0, Culture=neutral, PublicKeyToken=71e9bce111e9429c&quot; %&gt; &lt;%@ Register Tagprefix=&quot;Utilities [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string spstd4 {
            get {
                return ResourceManager.GetString("spstd4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;%-- _lcid=&quot;1033&quot; _version=&quot;16.0.4266&quot; _dal=&quot;1&quot; --%&gt;
        ///&lt;%-- _LocalBinding --%&gt;
        ///&lt;%@ Page language=&quot;C#&quot; MasterPageFile=&quot;~masterurl/default.master&quot;    Inherits=&quot;Microsoft.SharePoint.WebPartPages.WebPartPage,Microsoft.SharePoint,Version=16.0.0.0,Culture=neutral,PublicKeyToken=71e9bce111e9429c&quot;  %&gt; &lt;%@ Register Tagprefix=&quot;SharePoint&quot; Namespace=&quot;Microsoft.SharePoint.WebControls&quot; Assembly=&quot;Microsoft.SharePoint, Version=16.0.0.0, Culture=neutral, PublicKeyToken=71e9bce111e9429c&quot; %&gt; &lt;%@ Register Tagprefix=&quot;Utilities [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string spstd5 {
            get {
                return ResourceManager.GetString("spstd5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;%-- _lcid=&quot;1033&quot; _version=&quot;16.0.4266&quot; _dal=&quot;1&quot; --%&gt;
        ///&lt;%-- _LocalBinding --%&gt;
        ///&lt;%@ Page language=&quot;C#&quot; MasterPageFile=&quot;~masterurl/default.master&quot;    Inherits=&quot;Microsoft.SharePoint.WebPartPages.WebPartPage,Microsoft.SharePoint,Version=16.0.0.0,Culture=neutral,PublicKeyToken=71e9bce111e9429c&quot;  %&gt; &lt;%@ Register Tagprefix=&quot;SharePoint&quot; Namespace=&quot;Microsoft.SharePoint.WebControls&quot; Assembly=&quot;Microsoft.SharePoint, Version=16.0.0.0, Culture=neutral, PublicKeyToken=71e9bce111e9429c&quot; %&gt; &lt;%@ Register Tagprefix=&quot;Utilities [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string spstd6 {
            get {
                return ResourceManager.GetString("spstd6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;%-- _lcid=&quot;1033&quot; _version=&quot;16.0.4266&quot; _dal=&quot;1&quot; --%&gt;
        ///&lt;%-- _LocalBinding --%&gt;
        ///&lt;%@ Page language=&quot;C#&quot; MasterPageFile=&quot;~masterurl/default.master&quot;    Inherits=&quot;Microsoft.SharePoint.WebPartPages.WebPartPage,Microsoft.SharePoint,Version=16.0.0.0,Culture=neutral,PublicKeyToken=71e9bce111e9429c&quot;  %&gt; &lt;%@ Register Tagprefix=&quot;SharePoint&quot; Namespace=&quot;Microsoft.SharePoint.WebControls&quot; Assembly=&quot;Microsoft.SharePoint, Version=16.0.0.0, Culture=neutral, PublicKeyToken=71e9bce111e9429c&quot; %&gt; &lt;%@ Register Tagprefix=&quot;Utilities [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string spstd7 {
            get {
                return ResourceManager.GetString("spstd7", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;%-- _lcid=&quot;1033&quot; _version=&quot;16.0.4266&quot; _dal=&quot;1&quot; --%&gt;
        ///&lt;%-- _LocalBinding --%&gt;
        ///&lt;%@ Page language=&quot;C#&quot; MasterPageFile=&quot;~masterurl/default.master&quot;    Inherits=&quot;Microsoft.SharePoint.WebPartPages.WebPartPage,Microsoft.SharePoint,Version=16.0.0.0,Culture=neutral,PublicKeyToken=71e9bce111e9429c&quot;  %&gt; &lt;%@ Register Tagprefix=&quot;SharePoint&quot; Namespace=&quot;Microsoft.SharePoint.WebControls&quot; Assembly=&quot;Microsoft.SharePoint, Version=16.0.0.0, Culture=neutral, PublicKeyToken=71e9bce111e9429c&quot; %&gt; &lt;%@ Register Tagprefix=&quot;Utilities [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string spstd8 {
            get {
                return ResourceManager.GetString("spstd8", resourceCulture);
            }
        }
    }
}
