//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18408
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SPMeta2.Regression.Impl.Tests {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class TmpRes {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal TmpRes() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SPMeta2.Regression.Impl.Tests.TmpRes", typeof(TmpRes).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot;?&gt;
        ///&lt;webParts&gt;
        ///  &lt;webPart xmlns=&quot;http://schemas.microsoft.com/WebPart/v3&quot;&gt;
        ///    &lt;metaData&gt;
        ///      &lt;type name=&quot;SPMeta2.Containers.SandboxSolutionContainer.WebParts.ContainerWebPart.ContainerWebPart, SPMeta2.Containers.SandboxSolutionContainer, Version=1.0.0.0, Culture=neutral, PublicKeyToken=a18c22c531026525&quot; /&gt;
        ///      &lt;importErrorMessage&gt;$Resources:core,ImportErrorMessage;&lt;/importErrorMessage&gt;
        ///      &lt;Solution SolutionId=&quot;e9a61998-07f2-45e9-ae43-9e93fa6b11bb&quot; xmlns=&quot;http [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string SandboxWp {
            get {
                return ResourceManager.GetString("SandboxWp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot;?&gt;
        ///&lt;webParts&gt;
        ///  &lt;webPart xmlns=&quot;http://schemas.microsoft.com/WebPart/v3&quot;&gt;
        ///    &lt;metaData&gt;
        ///      &lt;type name=&quot;SPMeta2.Containers.SandboxSolutionContainer.WebParts.ContainerWebPart.ContainerWebPart, SPMeta2.Containers.SandboxSolutionContainer, Version=1.0.0.0, Culture=neutral, PublicKeyToken=a18c22c531026525&quot; /&gt;
        ///      &lt;importErrorMessage&gt;$Resources:core,ImportErrorMessage;&lt;/importErrorMessage&gt;
        ///    &lt;/metaData&gt;
        ///    &lt;data&gt;
        ///      &lt;properties&gt;
        ///        &lt;property name=&quot;Titl [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string SandboxWpNoS {
            get {
                return ResourceManager.GetString("SandboxWpNoS", resourceCulture);
            }
        }
    }
}
